CH90490 -- Adding distributed tracing to the JOOR PDF service
joor/url-to-pdf-api pull request #5
Opened 2020-11-09 20:47 UTC by rrwisner

ref -- https://app.clubhouse.io/joor/story/90490/instrument-joor-pdf-service-with-log-capture-and-distributed-tracing

2020-11-09 21:08 UTC, Humanetaking approved these changes
Looks good

2020-11-12 19:02 UTC, ktmq requested changes

2020-11-12 19:02 UTC, ktmq commented on src/config.js
> +  TRACING_ENV: process.env.DD_LOGS_INJECTION,
```suggestion
  TRACING_ENV: process.env.TRACING_ENV,
```
copy pasta?

2020-11-12 20:58 UTC, rrwisner commented on src/config.js
> +  TRACING_ENV: process.env.DD_LOGS_INJECTION,
That's weird, maybe 🤷

2020-11-12 22:34 UTC, ktmq approved these changes

2020-11-16 14:15 UTC, merged